-- JS Trendy Shop: marcas permitidas por categoría
-- Ejecuta este archivo una sola vez en Supabase > SQL Editor.

CREATE TABLE IF NOT EXISTS public.categoria_marcas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria text NOT NULL,
  marca text NOT NULL,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS categoria_marcas_unique_idx
ON public.categoria_marcas (lower(categoria), lower(marca));

ALTER TABLE public.categoria_marcas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read active category brands" ON public.categoria_marcas;
CREATE POLICY "Public can read active category brands"
ON public.categoria_marcas
FOR SELECT
TO anon, authenticated
USING (activo = true);

DROP POLICY IF EXISTS "Admin can read category brands" ON public.categoria_marcas;
CREATE POLICY "Admin can read category brands"
ON public.categoria_marcas
FOR SELECT
TO authenticated
USING (auth.uid() = 'd388d8a5-e1a5-44ce-a498-5fe297019d7e'::uuid);

DROP POLICY IF EXISTS "Admin can insert category brands" ON public.categoria_marcas;
CREATE POLICY "Admin can insert category brands"
ON public.categoria_marcas
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = 'd388d8a5-e1a5-44ce-a498-5fe297019d7e'::uuid);

DROP POLICY IF EXISTS "Admin can update category brands" ON public.categoria_marcas;
CREATE POLICY "Admin can update category brands"
ON public.categoria_marcas
FOR UPDATE
TO authenticated
USING (auth.uid() = 'd388d8a5-e1a5-44ce-a498-5fe297019d7e'::uuid)
WITH CHECK (auth.uid() = 'd388d8a5-e1a5-44ce-a498-5fe297019d7e'::uuid);

DROP POLICY IF EXISTS "Admin can delete category brands" ON public.categoria_marcas;
CREATE POLICY "Admin can delete category brands"
ON public.categoria_marcas
FOR DELETE
TO authenticated
USING (auth.uid() = 'd388d8a5-e1a5-44ce-a498-5fe297019d7e'::uuid);

-- Marcas iniciales para probar la configuración (seguro volver a ejecutar)
INSERT INTO public.categoria_marcas (categoria, marca, activo) VALUES
  ('Carteras','Guess',true),
  ('Carteras','Steve Madden',true),
  ('Carteras','Michael Kors',true),
  ('Ropa','Nike',true),
  ('Ropa','Adidas',true),
  ('Ropa','Puma',true),
  ('Calzado','Nike',true),
  ('Calzado','Adidas',true),
  ('Calzado','New Balance',true)
ON CONFLICT DO NOTHING;
