-- JS TRENDY SHOP V8.4 — categorías y marcas visuales configurables
-- Ejecutar una sola vez en Supabase SQL Editor.

create table if not exists public.tienda_categorias (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  etiqueta text not null,
  imagen text not null default '',
  activo boolean not null default true,
  orden integer not null default 0
);

create table if not exists public.tienda_marcas (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  imagen text not null default '',
  activo boolean not null default true,
  destacada boolean not null default true,
  orden integer not null default 0
);

alter table public.tienda_categorias enable row level security;
alter table public.tienda_marcas enable row level security;

drop policy if exists "Public can read active store categories" on public.tienda_categorias;
create policy "Public can read active store categories" on public.tienda_categorias
for select to anon, authenticated using (activo = true);

drop policy if exists "Admin can manage store categories" on public.tienda_categorias;
create policy "Admin can manage store categories" on public.tienda_categorias
for all to authenticated
using (auth.uid() = 'd388d8a5-e1a5-44ce-a498-5fe297019d7e'::uuid)
with check (auth.uid() = 'd388d8a5-e1a5-44ce-a498-5fe297019d7e'::uuid);

drop policy if exists "Public can read active store brands" on public.tienda_marcas;
create policy "Public can read active store brands" on public.tienda_marcas
for select to anon, authenticated using (activo = true);

drop policy if exists "Admin can manage store brands" on public.tienda_marcas;
create policy "Admin can manage store brands" on public.tienda_marcas
for all to authenticated
using (auth.uid() = 'd388d8a5-e1a5-44ce-a498-5fe297019d7e'::uuid)
with check (auth.uid() = 'd388d8a5-e1a5-44ce-a498-5fe297019d7e'::uuid);

insert into public.tienda_categorias (nombre, etiqueta, imagen, orden) values
('Bolsas','Bolsas','assets/categoria-bolsas.jpg',1),
('Calzado','Tenis','assets/categoria-tenis.jpg',2),
('Ropa','Ropa','assets/categoria-ropa.jpg',3),
('Perfumes','Perfumes','assets/categoria-perfumes.jpg',4),
('Accesorios','Accesorios','assets/categoria-accesorios.jpg',5),
('Relojes','Relojes','assets/categoria-relojes.jpg',6),
('Gorras','Gorras','assets/categoria-gorras.jpg',7),
('Lentes','Lentes','assets/categoria-lentes.jpg',8),
('Carteras','Carteras','assets/categoria-carteras.jpg',9),
('Ropa interior','Ropa interior','assets/categoria-ropa-interior.jpg',10),
('Calcetas','Calcetas','assets/categoria-calcetas.jpg',11)
on conflict (nombre) do nothing;

insert into public.tienda_marcas (nombre, imagen, destacada, orden) values
('Nike','assets/marca-nike.jpg',true,1),
('Adidas','assets/marca-adidas.jpg',true,2),
('Guess','assets/marca-guess.jpg',true,3),
('Michael Kors','assets/marca-michael-kors.jpg',true,4),
('Tommy Hilfiger','assets/marca-tommy-hilfiger.jpg',true,5),
('Calvin Klein','assets/marca-calvin-klein.jpg',true,6),
('Levi''s','assets/marca-levis.jpg',true,7),
('Puma','assets/marca-puma.jpg',true,8)
on conflict (nombre) do nothing;
